#pragma once
#ifndef ERRORCODES_HPP
# define ERRORCODES_HPP

enum ErrorCodes
{
	M_ERR_NOSUCHNICK = 401, // NICK, PRIVMSG, NOTICE
	M_ERR_NOSUCHCHANNEL = 403, // JOIN, PART, PRIVMSG, NOTICE
	M_ERR_CANNOTSENDTOCHAN = 404, // PRIVMSG, NOTICE
	M_ERR_UNKNOWNCOMMAND = 421, // (모든 명령어)
	M_ERR_NOMOTD = 422, // MOTD
	M_ERR_NONICKNAMEGIVEN = 431, // NICK
	M_ERR_ERRONEUSNICKNAME = 432, // NICK :오타가 있는 코드 (ERRONEOUSNICKNAME이 맞는 표현)
	M_ERR_NICKNAMEINUSE = 433, // NICK
	M_ERR_USERNOTINCHANNEL = 441, // KICK, MODE
	M_ERR_NOTONCHANNEL = 442, // PART, MODE, TOPIC, KICK
	M_ERR_USERONCHANNEL = 443, // INVITE
	M_ERR_NOTREGISTERED = 451, // (등록되지 않은 사용자에 대한 모든 명령어)
	M_ERR_NEEDMOREPARAMS = 461, // PASS, NICK, USER, JOIN, OPER, MODE
	M_ERR_ALREADYREGISTRED = 462, // USER, NICK
	M_ERR_PASSWDMISMATCH = 464, // OPER
	M_ERR_YOUREBANNEDCREEP = 465, // JOIN
	M_ERR_CHANNELISFULL = 471, // JOIN
	M_ERR_BADCHANMASK = 476, // JOIN
	M_ERR_UNKNOWNMODE = 472, // MODE
	M_ERR_INVITEONLYCHAN = 473, // JOIN
	M_ERR_BANNEDFROMCHAN = 474, // JOIN
	M_ERR_BADCHANNELKEY = 475, // JOIN
	M_ERR_NOPRIVILEGES = 481, // OPER
	M_ERR_CHANOPRIVSNEEDED = 482, // MODE, TOPIC, KICK, INVITE
	M_ERR_CANTKILLSERVER = 483, // KILL
	M_ERR_RESTRICTED = 484, // (다양한 명령어)
	M_ERR_UNIQOPPRIVSNEEDED = 485, // (서버 운영자 전용 명령어)
	M_ERR_NOOPERHOST = 491, // OPER
	M_ERR_UMODEUNKNOWNFLAG = 501, // MODE (사용자 모드 설정 시)
	M_ERR_USERSDONTMATCH = 502 // MODE (다른 사용자의 모드를 변경하려 할 때)
};
#endif
