#pragma once
#ifndef REPLYCODES_HPP
# define REPLYCODES_HPP

enum ReplyCodes
{
    M_RPL_WELCOME = 001, // 서버에 처음 연결했을 때 (NICK, USER)
    M_RPL_YOURHOST = 002, // 서버에 처음 연결했을 때 (NICK, USER)
    M_RPL_CREATED = 003, // 서버에 처음 연결했을 때 (NICK, USER)
    M_RPL_MYINFO = 004, // 서버에 처음 연결했을 때 (NICK, USER)
    M_RPL_BOUNCE = 005, // 서버 메시지 (NICK, USER)
    M_RPL_USERHOST = 302, // USERHOST 요청에 대한 응답 (USERHOST)
    M_RPL_ISON = 303, // ISON 요청에 대한 응답 (ISON)
    M_RPL_AWAY = 301, // 사용자가 away 상태일 때 (PRIVMSG, NOTICE)
    M_RPL_UNAWAY = 305, // 사용자가 away 상태를 해제했을 때 (AWAY)
    M_RPL_NOWAWAY = 306, // 사용자가 away 상태로 설정되었을 때 (AWAY)
    M_RPL_WHOISUSER = 311, // WHOIS 요청에 대한 응답 (WHOIS)
    M_RPL_WHOISSERVER = 312, // WHOIS, 사용자가 연결된 서버 정보 (WHOIS)
    M_RPL_WHOISOPERATOR = 313, // WHOIS, 사용자가 IRC 오퍼레이터인지 (WHOIS)
    M_RPL_WHOWASUSER = 314, // WHOWAS 요청에 대한 응답, 과거 사용자 정보 (WHOWAS)
    M_RPL_ENDOFWHO = 315, // WHO 요청에 대한 응답 종료 (WHO)
    M_RPL_WHOISIDLE = 317, // WHOIS, 사용자의 유휴 시간 정보 (WHOIS)
    M_RPL_ENDOFWHOIS = 318, // WHOIS 요청에 대한 응답 종료 (WHOIS)
    M_RPL_WHOISCHANNELS = 319, // WHOIS, 사용자가 참여하고 있는 채널 정보 (WHOIS)
    M_RPL_LISTSTART = 321, // LIST 요청 시작 (LIST)
    M_RPL_LIST = 322, // LIST, 채널과 그 채널의 사용자 수 (LIST)
    M_RPL_LISTEND = 323, // LIST 요청 종료 (LIST)
    M_RPL_CHANNELMODEIS = 324, // 채널의 현재 모드 표시 (MODE)
    M_RPL_NOTOPIC = 331, // 채널에 토픽이 설정되지 않았을 때 (TOPIC)
    M_RPL_TOPIC = 332, // 채널의 현재 토픽 (TOPIC)
    M_RPL_TOPICWHOTIME = 333,
    M_RPL_INVITING = 341, // INVITE 요청에 대한 응답, 초대중인 사용자 (INVITE)
    M_RPL_SUMMONING = 342, // SUMMON 요청에 대한 응답 (SUMMON)
    M_RPL_VERSION = 351, // VERSION 요청에 대한 응답, 서버의 버전 정보 (VERSION)
    M_RPL_WHOREPLY = 352, // WHO 요청에 대한 응답, 사용자 정보 (WHO)
    M_RPL_NAMREPLY = 353, // NAMES 요청에 대한 응답, 채널 내의 모든 사용자 목록 (NAMES)
    M_RPL_LINKS = 364, // LINKS 요청에 대한 응답, 서버 연결 리스트 (LINKS)
    M_RPL_ENDOFLINKS = 365, // LINKS 요청 종료 (LINKS)
    M_RPL_ENDOFNAMES = 366, // NAMES 요청 종료 (NAMES)
    M_RPL_BANLIST = 367, // 채널의 밴 리스트 (MODE +b)
    M_RPL_ENDOFBANLIST = 368, // 밴 리스트 요청 종료 (MODE +b)
    M_RPL_ENDOFWHOWAS = 369, // WHOWAS 요청 종료 (WHOWAS)
    M_RPL_INFO = 371, // INFO 요청에 대한 응답, 서버 정보 (INFO)
    M_RPL_MOTD = 372, // MOTD (Message of the Day) 요청에 대한 응답 (MOTD)
    M_RPL_ENDOFINFO = 374, // INFO 요청 종료 (INFO)
    M_RPL_MOTDSTART = 375, // MOTD 시작 (MOTD)
    M_RPL_ENDOFMOTD = 376, // MOTD 종료 (MOTD)
    M_RPL_YOUREOPER = 381, // 사용자가 IRC 오퍼레이터로 승격되었음을 알림 (OPER)
    M_RPL_REHASHING = 382, // REHASH 요청에 대한 응답 (REHASH)
    M_RPL_YOURESERVICE = 383, // 서비스로 등록됨 (SERVICE)
    M_RPL_TIME = 391, // 서버의 현재 시간 (TIME)
    M_RPL_USERSSTART = 392, // USERS 요청 시작 (USERS)
    M_RPL_USERS = 393, // USERS, 시스템에 로그인한 사용자 목록 (USERS)
    M_RPL_ENDOFUSERS = 394, // USERS 요청 종료 (USERS)
    M_RPL_NOUSERS = 395 // 시스템에 로그인한 사용자가 없음 (USERS)
};

#endif
